name: 'attribution_use_case'
version: '1.0'
require-dbt-version: ">=0.17.0"
config-version: 2

source-paths: ["models"]
data-paths: ["data"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  # number of trailing hours to re-sessionize for.
  # events can come in late and we want to still be able to incorporate
  # them into the definition of a session without needing a full refresh.
  sessionization_trailing_window: 3

  # sessionization inactivity cutoff: of there is a gap in page view times
  # that exceeds this number of seconds, the subsequent page view will
  # start a new session.
  inactivity_cutoff: 30 * 60

  # If there are extra columns you wish to pass through this package,
  # define them here. Columns will be included in the `web_sessions`
  # model as `first_<column>` and `last_<column>`. Extremely useful when
  # using this package on top of unioned sources, as you can then
  # pass through a column indicating which source the data is from.
  pass_through_columns: []
